### PR TITLE
new storybook component: fetching resources error page

### LINKED ISSUE #141: Create a react storybook component for " fetching resources error page" from a design
The design can be found on [this figma file](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=249%3A52).

This issue is a subtask of [this bigger parent issue](https://github.com/Ngoakor12/coding-resource-finder/issues/129), you can go there to get a zoomed out/ bigger picture of this task

### PR DESCRIPTION
**Pull request by chetanchandel31**
## 🛠️ Fixes issue(s)

Closes #141

## ✔️ Checklist (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

here is a storybook component for "fetching resources error page" which follows the [linked design](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=249%3A52)

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Ngoakor12** [comment]
That was fast! First impressions is that it looks bang on. However, I'm not on my machine right now so I'll only be able to pull it in and double check everything later.

**Comment by chetanchandel31** [comment]
no worries, i'll wait 🙂

**Review by Ngoakor12 — APPROVED** [review]
Looks good enough

Thank you for taking your time to contribute  :+1:

**Review by Ngoakor12 — APPROVED** [review]
Looks good enough

Thank you for taking your time to contribute  :+1:

**Pull request merged**
