### PR TITLE
add storybook for component building

### LINKED ISSUE #130: Feat: Add storybook for component building
**Is your feature request related to a problem? Please describe.**
Yes, I need to have designs ready before I can let people work on features

**Describe the solution you'd like**
Use [Storybook](https://storybook.js.org/) to help with visualizing components without worrying about data and functionality. That way others can sort of work on the designs aswell and implement them as components

**Describe alternatives you've considered**
I keep making designs for things to be implemented and then allow others to work on things when the designs are finalized which is not very sustainable

**Additional context**
At least one component should be added to the storybook to show that everything works as expected. You can ask me if you want  a component to implement.

### PR DESCRIPTION
**Pull request by ekiira**
## 🛠️ Fixes issue(s)

Closes #130

## 👨‍💻 Change(s) proposed

I added Storybook to the application and added the SearchForm component to Storybook.

## ✔️ Checklist (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Ngoakor12** [comment]
This is a big boy! mostly like due to the lock file :sweat_smile:  Will review this today, thanks for your patience :lotus_position:

**Comment by ekiira** [comment]
Yes, it's the lock file.
Alright, thanks.

**Review by Ngoakor12 — APPROVED** [review]
"It looks like a duck and quacks like one, so it's definitely a duck" - some genius

**Comment by Ngoakor12** [comment]
Thank you very much for the contribution @ekiira :)

**Pull request merged**
