### PR TITLE
Refactor: api calls - fetch all resources at once

### PR DESCRIPTION
**Pull request by senali-d**
1. Render all the data when page load
2. Remove "Load 20 more resources" button

### CODE REVIEW

**Review by Ngoakor12 — CHANGES_REQUESTED** [review]
Hey, thanks again for take a stab at this issue. Some tasks are done, others still need work, here's a list to track everything:
- [x] remove "load 20 more resources" button.
- [ ] fetch all resources at once, some concurrently(I'll elaborate further below)
- [ ] "load all resources" button should still work and reveal all resources as opposed to the first page resources

**Comment by Ngoakor12** [comment]
I know the issue description is a bit rough but can you read over it one more time to see what's needed for this issue to be merged.

The main task of this issue is to make fetch all resources on load. This should ofcourse not take forever so that's why I want it to fetch the first page of resources depending on which page you're in. For example, if you enter the site via "https://base_url/topics" then the website should fetch "https://api_url/topics/1" and render resources on the first page of topics, but also fetch "https://api_url/all" but in the background using [**`promise.all`**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all). same for all the other pages (all and projects)

Please don't be afraid to break things and remove code within reason, the whole fetching mechanism is a bit of the mess at the moment. 

Let me know if you can't continue working on this issue, maybe you underestimated it, there won't be any hard feelings.

Hit me up if you have more clarifying questions :)

**Comment by senali-d** [comment]
Hey [@Ngoakor12](https://github.com/Ngoakor12),

I have confusion on the requirement. 

> For example, if you enter the site via "https://base_url/topics" then the website should fetch "https://api_url/topics/1" and render resources on the first page of topics, but also fetch "https://api_url/all" but in the background using [promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).

1. Fetch the first page of topics `https://api_url/topics/1`
2. Fetch all `https://api_url/all` (in background)

When you render only first page of topics, also remove the "load 20 more resources" button. There is no any way for user to render next items in the pages. "load all resources" is the solution for that.

**Comment by Ngoakor12** [comment]
There is a way, checkout to the hash to see how it was implemented before(8a2c12f6c4797c1931548b311cfd28bf085171f4).

Basically(using the example for only all resources page):
You have **three states** for resources, one for the _first page resources_, one for _all the resources_ and another for _the resources you render_ on the page. On first load everything is fetched, all resources populate all resource state, page resources populate page resources state **and** rendered resources page.

All resources are shown in two instances:
- when the user starts searching
- when the user presses load more resources

How all resources are displayed:
- populating the rendered resources state.

The reason why there's a separate state for rendered resources is because the **search feature** filters the rendered resources array when looking for resources and that state would be lost if the other two states hadn't backed up the resources. for when the user is no longer searching.

**Comment by Ngoakor12** [comment]
Hey @senali-d you still working on this? I can take it off you if not, just let me know.

**Comment by senali-d** [comment]
[@Ngoakor12](https://github.com/Ngoakor12) yes. I'm working on this task.

**Comment by senali-d** [comment]
Hey [@Ngoakor12](https://github.com/Ngoakor12),
- [x] fetch all resources at once, some concurrently(I'll elaborate further below)
- [x] "load all resources" button should still work and reveal all resources as opposed to the first page resources

I think confusion of the requirement sorted now. If not let me know.

**Comment by Ngoakor12** [comment]
Hey, saw that you pushed some changes, I'll be sure to sit down and review them later today🤙

**Review by Ngoakor12 — CHANGES_REQUESTED** [review]
Hey Senali, appreciate your persistence on this issue. Apologies for the late review, something came up.

Something I need to clarify that may help you in successfully solving this issue: **The main idea of this task is to limit the number of network requests past the initial render**.

**Task-wise**
On-track:
- the "load all resources" buttons works as expected, no network requests are made when they are clicked
- the first render is almost there. One thing to correct, visiting the website via a certain route e.g `https://url/topics` the only network requests that should occur should be `https://api_url/all/topics/1` and `https://api_url/topics`. Only those two. Here are the network requests that happen at the moment
image

Same thing applies for the othe routes(/ and /projects)

Off-track:
- The search feature now makes a network request on each key stroke which is not ideal if the main idea of this issue is to reduce the number of network calls. The search feature shouldn't be touched as much as you have

Bonus:
- `loadMoreResources()` function is no longer required, you can remove it.

**Comment by senali-d** [comment]
Hey Ngoakor12,
I'll work on requested change and back to you.

**Comment by Ngoakor12** [comment]
> Hey Ngoakor12, I'll work on requested change and back to you.

It's been over 2 weeks, I assume you haven't had the chance work on this issue, can I reassign it?

**Comment by Ngoakor12** [comment]
Assignee not responsive.

**Pull request closed without merging**
