### PR TITLE
Added consistent focus state

### LINKED ISSUE #185: Focus state should be consistent for all keyboard focus(able) elements
**Describe the bug**

The focus state is not consistent

**To Reproduce**

Focus state should be consistent for all elements

**Screenshots**

example of correct focus state:
image

example of wrong focus state:
image

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 

**Additional context**

### PR DESCRIPTION
**Pull request by sudeepmahato16**
I have added consistent focus state for all elements.

### CODE REVIEW

**Comment by Ngoakor12** [comment]
@sudeepmahato16 Next time... **Please ask to work on an issue, wait to be assigned and then open a PR just like it's mentioned in the conrtibuting guidelines**. Otherwise I will reject your future PRs.

I will however look at this one later today

**Comment by sudeepmahato16** [comment]
Thank you for your message. I apologize for not following the established guidelines for contributing. I will make sure to ask to work on an issue, wait to be assigned, and then open a PR in the future. I appreciate your willingness to still review my current PR, and I hope to improve my contributions to this project going forward.

**Review by Ngoakor12 — APPROVED** [review]
It's working as expected. well done :muscle: 

It's cool that you used the universal selector to avoid too much copy pasta code. I hadn't thought of that to be honest :sweat_smile:

**Comment by Ngoakor12** [comment]
oooh @sudeepmahato16 next time use the PR template aswell, it's there for a purpose.

**Comment by sudeepmahato16** [comment]
okay☺

**Pull request merged**
