### PR TITLE
fixed : Resource type filtering stuck when both chips are selected an…

### LINKED ISSUE #162: Resource type filtering  stuck when both chips are selected and unselected
**Describe the bug**

selecting and unselecting resource type chips defaults to all topics

**To Reproduce**

1. select a resource type filter chip
2. unselect it and make sure no resouce type is selected

**Expected behavior**

unselecting a resource chip should result a mix of the resources not only topics

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 

**Additional context**

### PR DESCRIPTION
**Pull request by MohammadRostami71**
…d unselected #162

## ✔️ Checklist (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Ngoakor12** [comment]
@MohammadRostami71 thanks for taking your time to work on this. Question...

Were you able reproduce the bug in the issue?

I can't seem to be able to reproduce it, so I'm afraid this PR may not be needed since the bug seems to have disappeared.

**Comment by MohammadRostami71** [comment]
@Ngoakor12 
When I ran the program, after clicking on the chips and applying the filter, the program crashed. After taking the logs, I found out that the component in which the changes occurred does not react to the changes correctly, this problem was solved by using useEffect. Very surprising that you can't reproduce the problem!

**Comment by Ngoakor12** [comment]
That is very strange. The deployed/prod website doesn't seem to have issues.

I will try checking locally and see if that's the reason why I opened the issue in the first place. Will get back to you as soon as I do that.

**Comment by Ngoakor12** [comment]
> @Ngoakor12 When I ran the program, after clicking on the chips and applying the filter, the program crashed. After taking the logs, I found out that the component in which the changes occurred does not react to the changes correctly, this problem was solved by using useEffect. Very surprising that you can't reproduce the problem!

- What error did you get when the website crashed?
- Do you see any issues on the [deployed website](https://coding-resource-finder.ngoako.dev/resources)?

**Comment by MohammadRostami71** [comment]
Dear @Ngoakor12

I can't reproduce the problem, maybe merging some issues was solved this problem.

I should have taken a screenshot of the problem, unfortunately I didn't

**Comment by Ngoakor12** [comment]
No problem @MohammadRostami71. I will be closing this PR and the related issues in the meantime. You are always welcome to contribute if you see an issue you like.

Thanks again for lending a hand. It's really appreciated, hopefully everything goes well next time :smile: :see_no_evil:

**Pull request closed without merging**
