### PR TITLE
fix: Pull request template not showing up

### LINKED ISSUE #85: Bug: Pull request template not showing up
Whenever a PR is made, a pull request template should prefill the title and description fields, but it does not show up. Poke around and see if you can find the problem with the template and a fix for it.

### PR DESCRIPTION
**Pull request by Dun-sin**
fixes #85

### CODE REVIEW

**Review by Ngoakor12 — APPROVED** [review]
Looks good enough, hopefully works.

**Comment by Ngoakor12** [comment]
@Dun-sin This PR fixes the problem, thanks for taking the time to contribute :)

**Comment by Dun-sin** [comment]
> @Dun-sin This PR fixes the problem, thanks for taking the time to contribute :)

You are welcome, I think it's because you placed it in it's own folder. Maybe take a note for next time

**Comment by Ngoakor12** [comment]
> > @Dun-sin This PR fixes the problem, thanks for taking the time to contribute :)
> 
> You are welcome, I think it's because you placed it in it's own folder. Maybe take a note for next time

Yeah, I didn't read the documentation, I did it how I did the issues templates and they are working fine XD

**Comment by Dun-sin** [comment]
> Yeah, I didn't read the documentation, I did it how I did the issues templates and they are working fine XD

Issues work fine in a folder

**Pull request merged**
