### PR TITLE
Feat add tabs for all projects and topics resources

### LINKED ISSUE #62: feat: add tabs for all, projects, and topics resources
**Is your feature request related to a problem? Please describe.**
When I search for a resource I sometimes just want to browse topics and other times projects.

**Describe the solution you'd like**
Tabs in resource page, above or below the search input and filter shortcuts named: **all**, **topics**,  and **projects**

**Describe alternatives you've considered**
An alternative solution would be to extend the search feature to search by resource type.
Another was to add a shortcut like the topics shortcuts.

**Additional context**
Mockup below. Figma file can be found [here](https://www.figma.com/file/kZxZ3wqIDmMJ63LnagRUcf/coding-resource-finder?node-id=21%3A22)
image

### PR DESCRIPTION
**Pull request by matthewbub**
Issue: https://github.com/Ngoakor12/coding-resource-finder/issues/62 

This MR introduces the `All` `Projects` and `Topics` resource tabs into the primary Search form. Styling has been tailered to match both the current design and mock. 

Walkthrough video demoing new feature locally: https://youtu.be/ALhFd0DnM8s
Screen Shot 2022-05-07 at 7 58 21 PM

Feel free to let me know if you have any questions 🙂

### CODE REVIEW

**Review by Ngoakor12 — CHANGES_REQUESTED** [review]
Hey @yeahmat , thank you for taking the time to contribute. It's really appreciated.

First thing, this is one of the most thought out MR I've ever received, granted it's the second PR by anyone other than myself on this project. The video is a nice touch, so convenient that I might have to start using it to make MRs.

After looking at your submission however I do notice that the direction and wording of the project is poor on my end. TL/DR: I want the tabs all, topics and projects to be pages on their own and not just filter tabs, so searching a resource in topics should only search topics, same with project and all resources. I'll leave you with two choices, considering that the scope of the MR is bigger than I expected. 

1. **Easier:** Just update the tab labels so that `topic` is topics and `project` is `projects`. Make sure that it works as it does now. I'll happily merge it and open another issue for updating the functionality to act as pages
2. **Harder:** Also update the labels to be in plural. Turn the tabs into pages(knowledge of react router dom is required). Update the default  home route to be `resources/all`. Clicking on `topics` "tab" should take us to `resources/topics`. Projects should be a page and have an updated route too. Fetching resources may need to updated so that you get just topics and just projects for their respective pages. To find out how to fetch those topics and projects resources on their own look at the API in `backend/src/api.js. This is the more time consuming option so I understand if you go with the other one.

Let me know if you need me to clarify anything. Thanks again for taking the time

**Comment by matthewbub** [comment]
Hey I'm glad you liked the video, I hope it helped convey my thought process 💭  <br> Option 2 sounds a bit more fleshed-out, and also in-line with what you want. We could head that direction 👍  I'll be working on it throughout my day today (It's Mother's day here)

---
Just a few questions to confirm my understanding

> Update the default home route to be resources/all

Are there plans to replace the `/` with a different screen e.g landing page? The `all` tab appears to be the default view - but I could have a misunderstanding there. If we update this page's route to `/resources/all` what will the default route render?  

While that gets sorted, I will leave the `all` as the base route for now to avoid breaking changes 🙌 

### Tasks remaining 
This is currently how I am seeing the tasks remaining. Please feel free to copy/paste these if edits are needed 
- [x] update tab names to be plural. **Currently:** `Topic` `Project` **Should Be:** `Topics` `Projects`
- [x] `Topics` should direct to `/resources/topics` 
- [x] `Projects` should direct to `/resources/projects` 
- [x] `Topics` page should filter results that contain the `type: "topic"` value
- [x] `Projects` page should filter results that contain the `type: "project"` value

**Comment by Ngoakor12** [comment]
I don't plan on using the default route for anything so here's what the final routes should look like instead:
- `/` should represent "all" resources
- `/topics`  should represent "topics"
- `/projects` should represent "projects"
- `/bookmarks` already represent bookmarks

**Comment by matthewbub** [comment]
I am about to step away from the desk for a bit but wanted to push what I have. This is working as-is, but I have noticed some buggy behavior in areas. I can take a deeper look a bit later. Basically an MVP at the moment.

**Review by Ngoakor12 — COMMENTED** [review]
Hey, thanks again. **I looked at the preview deploy and it seems to function as expected**. The only issues I see is how to indicate resources nav item as active for all,topics and project sub nav items. The other one is how it sort of updates all resources without you clicking "load all resources" button instead of the 20 resource limit if you go back and forth a tab/page. That's a long standing issue I know about. Making multiple api calls being another problem, which can be dealt with later. 

All of the above mentioned issues are not that major and can be dealt with as separate issues. **Are there any other issues I didn't mention/catch?** Otherwise **I'll pull the code down on my machine for further review and merge it if I don't find more issues.**

**Comment by matthewbub** [comment]
> All of the above mentioned issues are not that major and can be dealt with as separate issues. 

Confirmed 👍 

> Are there any other issues I didn't mention/catch? 

I believe you've addressed what I was seeing from my end. What initially had me confused, was if I select a suggestion e.g`PHP` it would filter how we would expect. If I click the same suggestion again, it looks to cause some unexpected behavior. But upon further review I do not think this was a bug introduced with my MR as I am seeing the same thing in the current deploy. 

This MR is ready for local testing, if you bump into anything you'd like me to take a look at, feel free to let me know 🙂 

also, apologies for the delay in getting back to you, Monday came up pretty quick!

**Comment by Ngoakor12** [comment]
Hey, had a look on my local machine and it's good to go, nothing crazy or out of the ordinary jumping at me. Thanks again for taking your time(mothers day :) ) to work on this.

**Pull request merged**
